version: '3.8'

services:
  back:
    image: "fastapi_starter:1.0.0"
    depends_on:
      - db
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    ports:
      - "8888:8000"
    volumes:
      - ./backend:/usr/src/app/backend:cached
      - ./db:/usr/src/app/db:cached
      - ./scripts:/usr/src/app/scripts:cached
    working_dir: /usr/src/app/scripts
    command: bash -c "./run.sh"
    networks:
      - fastapi_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env

  front:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    networks:
      - fastapi_network

  db:
    image: "fastapi_starter_db:0.1.0"
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    restart: always
    tty: true
    expose:
      - "3306"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d:cached
      - ./log/db:/var/log/mysql:cached
    networks:
      - fastapi_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env

networks:
  default:
    external:
      name: bridge
  fastapi_network:
    name: fastapi_network
    driver: bridge
    external: true