"""create_users

Revision ID: 101d9cdafd2f
Revises: ff4d47f6a0af
Create Date: 2022-11-15 23:55:07.565284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '101d9cdafd2f'
down_revision = 'ff4d47f6a0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted', sa.DateTime(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.drop_column('users', 'deleted')
    # ### end Alembic commands ###
